apiVersion: eksctl.io/v1alpha4
kind: ClusterConfig
metadata:
  name: cluster-mreferre
  region: us-west-2
nodeGroups:
  - name: ng-1-workers
    labels:
      role: workers
    instanceType: m5.xlarge
    desiredCapacity: 3
    privateNetworking: true
